### ISSUE TITLE
Primary action button guidelines missing link to action buttons

### ISSUE THREAD

**Issue by Blackbaud-MattGregg** [blackbaud/skyux-design#146]
https://developer.blackbaud.com/skyux/design/guidelines/page-layouts#primary-action-guidelines

In last button, reference to Action button missing link.

**Comment by blackbaud-johnly** [comment]
Addressed in https://github.com/blackbaud/skyux2-docs/pull/133, which has been merged.

**Comment by Blackbaud-ToddRoberts** [comment]
Fixed
