### ISSUE TITLE
Grid multiselect documentation

### ISSUE THREAD

**Issue by Blackbaud-ToddRoberts** [blackbaud/skyux-design#205]

**Comment by Blackbaud-ToddRoberts** [comment]
https://blackbaudinc.box.com/s/8mfzaa76pev6q7ptbu5pqwcxj016xdwf

**Comment by blackbaud-johnly** [comment]
Should this be closed in light of the docs that were published in https://github.com/blackbaud/skyux2-docs/pull/183?
