### ISSUE TITLE
Input field masking (Idea)

### ISSUE THREAD

**Issue by Blackbaud-MattGregg** [blackbaud/skyux-design#223]
Approved April 15, 2019
https://blackbaudinc.box.com/s/k5e2t9tqu76vlzwiaw75jbn174tfy44a

**Comment by Blackbaud-ToddRoberts** [comment]
After a lot of work, technical issues seem insurmountable. Alternate solution implemented for the main case around date validation. Closing for now until this becomes a high priority.
